version: 0.2

env:
    parameter-store:
        TERRAFORM_STATEFILE_BUCKET: "terraformStateFileS3Bucket"
        TERRAFORM_STATELOCK_DD_TABLE: "terraformStateLockDDTable"
        ENV_NAME: "envName"

phases:
    build:
        commands:
        - cd "$CODEBUILD_SRC_DIR"
        - node putValues.js
        - echo $TERRAFORM_STATEFILE_BUCKET
        - echo $TERRAFORM_STATELOCK_DD_TABLE
        - echo $ENV_NAME
        - cat envs/stage/terragrunt.hcl
        - cd envs/stage
        - terragrunt run-all apply --terragrunt-non-interactive      
