version: 0.2

env:
    parameter-store:
        TERRAFORM_STATEFILE_BUCKET: "terraformStateFileS3Bucket"
        TERRAFORM_STATELOCK_DD_TABLE: "terraformStateLockDDTable"
        ENV_NAME: "envName"

phases:
    build:
        commands:
        - cd "$CODEBUILD_SRC_DIR"
        - cd envs/stage
        - terragrunt run-all apply --terragrunt-parallelism 1 --terragrunt-non-interactive
        
