version: 0.2

env:
    parameter-store:
        TERRAFORM_STATEFILE_BUCKET: "terraformStateFileS3Bucket"
        TERRAFORM_STATELOCK_DD_TABLE: "terraformStateLockDDTable"
        ENV_NAME: "envName"

phases:
    build:
        commands:
        - cd "$CODEBUILD_SRC_DIR"
        - aws sts get-caller-identity
        - node putValues.js
        - echo $TERRAFORM_STATEFILE_BUCKET
        - echo $TERRAFORM_STATELOCK_DD_TABLE
        - echo $ENV_NAME
        - cat envs/stage/terragrunt.hcl
        - cd envs/stage
        # - cd envs/stage/infra/12-glue/crawler
        # - terragrunt init
        # - terragrunt apply --auto-approve
        - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
        - terragrunt run-all destroy --terragrunt-parallelism 1 --terragrunt-non-interactive      
