version: 0.2
phases:
    build:
        commands:
        - cd "$CODEBUILD_SRC_DIR"
        - cd envs/test/
        - codebuild-breakpoint
        - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
        - terragrunt run-all apply --terragrunt-parallelism 1  --terragrunt-non-interactive
