# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "319925118739-statefile"
    dynamodb_table = "tf-statelock"
    encrypt        = true
    key            = "test/./terraform.tfstate"
    region         = "us-east-1"
  }
}
