# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "993809450021-test-statefiles"
    dynamodb_table = "tf-statelock"
    encrypt        = true
    key            = "test/./terraform.tfstate"
    region         = "us-east-1"
  }
}
